In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Display settings
pd.set_option('display.max_columns', 100)
sns.set(style="whitegrid", palette="muted", font_scale=1.1)

In [3]:
# Load Matches data
matches_df = pd.read_csv("../data/Matches.csv")

# Load Elo Ratings
elo_df = pd.read_csv("../data/EloRatings.csv")

C:\Temp\ipykernel_12984\250168887.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  matches_df = pd.read_csv("../data/Matches.csv")

In [4]:
# Shape and preview
print("Matches shape:", matches_df.shape)
matches_df.head()

Matches shape: (230557, 48)

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway,FTResult,HTHome,HTAway,HTResult,HomeShots,AwayShots,HomeTarget,AwayTarget,HomeFouls,AwayFouls,HomeCorners,AwayCorners,HomeYellow,AwayYellow,HomeRed,AwayRed,OddHome,OddDraw,OddAway,MaxHome,MaxDraw,MaxAway,Over25,Under25,MaxOver25,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
0,F1,2000-07-28,NaN,Marseille,Troyes,1686.34,1586.57,0.0,0.0,0.0,0.0,3.0,1.0,H,2.0,1.0,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.65,3.3,4.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,2000-07-28,NaN,Paris SG,Strasbourg,1714.89,1642.51,0.0,0.0,0.0,0.0,3.0,1.0,H,1.0,1.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.60,3.4,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F2,2000-07-28,NaN,Wasquehal,Nancy,1465.08,1633.80,0.0,0.0,0.0,0.0,0.0,1.0,A,0.0,1.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,2000-07-29,NaN,Auxerre,Sedan,1635.58,1624.22,0.0,0.0,0.0,0.0,0.0,1.0,A,0.0,1.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.70,3.3,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,2000-07-29,NaN,Bordeaux,Metz,1734.34,1673.11,0.0,0.0,0.0,0.0,1.0,1.0,D,1.0,0.0,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.65,3.3,4.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Basic info
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230557 entries, 0 to 230556
Data columns (total 48 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Division     230557 non-null  object
 1   MatchDate    230557 non-null  object
 2   MatchTime    99072 non-null   object
 3   HomeTeam     230557 non-null  object
 4   AwayTeam     230557 non-null  object
 5   HomeElo      141597 non-null  float64
 6   AwayElo      141528 non-null  float64
 7   Form3Home    229057 non-null  float64
 8   Form5Home    229057 non-null  float64
 9   Form3Away    229057 non-null  float64
 10  Form5Away    229057 non-null  float64
 11  FTHome       230554 non-null  float64
 12  FTAway       230554 non-null  float64
 13  FTResult     230554 non-null  object
 14  HTHome       175977 non-null  float64
 15  HTAway       175977 non-null  float64
 16  HTResult     175977 non-null  object
 17  HomeShots    114735 non-null  float64
 18  AwayShots    114738 non-null  float64
 19  HomeTarget   113929 non-null  float64
 20  AwayTarget   113932 non-null  float64
 21  HomeFouls    113973 non-null  float64
 22  AwayFouls    113973 non-null  float64
 23  HomeCorners  114363 non-null  float64
 24  AwayCorners  114363 non-null  float64
 25  HomeYellow   119298 non-null  float64
 26  AwayYellow   119299 non-null  float64
 27  HomeRed      119299 non-null  float64
 28  AwayRed      119297 non-null  float64
 29  OddHome      227527 non-null  float64
 30  OddDraw      227527 non-null  float64
 31  OddAway      227527 non-null  float64
 32  MaxHome      202922 non-null  float64
 33  MaxDraw      202922 non-null  float64
 34  MaxAway      202922 non-null  float64
 35  Over25       148398 non-null  float64
 36  Under25      148397 non-null  float64
 37  MaxOver25    148398 non-null  float64
 38  MaxUnder25   148397 non-null  float64
 39  HandiSize    156733 non-null  float64
 40  HandiHome    156475 non-null  float64
 41  HandiAway    156451 non-null  float64
 42  C_LTH        112602 non-null  float64
 43  C_LTA        112602 non-null  float64
 44  C_VHD        112602 non-null  float64
 45  C_VAD        112602 non-null  float64
 46  C_HTB        112602 non-null  float64
 47  C_PHB        112602 non-null  float64
dtypes: float64(41), object(7)
memory usage: 84.4+ MB

In [6]:
# Null values
matches_df.isnull().sum().sort_values(ascending=False)

MatchTime      131485
C_PHB          117955
C_HTB          117955
C_VAD          117955
C_VHD          117955
C_LTA          117955
C_LTH          117955
HomeTarget     116628
AwayTarget     116625
AwayFouls      116584
HomeFouls      116584
HomeCorners    116194
AwayCorners    116194
HomeShots      115822
AwayShots      115819
AwayRed        111260
HomeYellow     111259
HomeRed        111258
AwayYellow     111258
AwayElo         89029
HomeElo         88960
MaxUnder25      82160
Under25         82160
MaxOver25       82159
Over25          82159
HandiAway       74106
HandiHome       74082
HandiSize       73824
HTHome          54580
HTResult        54580
HTAway          54580
MaxHome         27635
MaxDraw         27635
MaxAway         27635
OddHome          3030
OddAway          3030
OddDraw          3030
Form3Home        1500
Form5Home        1500
Form3Away        1500
Form5Away        1500
FTResult            3
FTHome              3
FTAway              3
MatchDate           0
AwayTeam            0
HomeTeam            0
Division            0
dtype: int64

In [7]:
matches_df.columns.tolist()

['Division',
 'MatchDate',
 'MatchTime',
 'HomeTeam',
 'AwayTeam',
 'HomeElo',
 'AwayElo',
 'Form3Home',
 'Form5Home',
 'Form3Away',
 'Form5Away',
 'FTHome',
 'FTAway',
 'FTResult',
 'HTHome',
 'HTAway',
 'HTResult',
 'HomeShots',
 'AwayShots',
 'HomeTarget',
 'AwayTarget',
 'HomeFouls',
 'AwayFouls',
 'HomeCorners',
 'AwayCorners',
 'HomeYellow',
 'AwayYellow',
 'HomeRed',
 'AwayRed',
 'OddHome',
 'OddDraw',
 'OddAway',
 'MaxHome',
 'MaxDraw',
 'MaxAway',
 'Over25',
 'Under25',
 'MaxOver25',
 'MaxUnder25',
 'HandiSize',
 'HandiHome',
 'HandiAway',
 'C_LTH',
 'C_LTA',
 'C_VHD',
 'C_VAD',
 'C_HTB',
 'C_PHB']

In [10]:
print("Unique Home Teams:", matches_df["HomeTeam"].nunique())
print("Unique Away Teams:", matches_df["AwayTeam"].nunique())

Unique Home Teams: 1214
Unique Away Teams: 1206

In [11]:
# Combined unique teams
teams = pd.unique(matches_df[["HomeTeam", "AwayTeam"]].values.ravel())
print("Total Unique Teams:", len(teams))

Total Unique Teams: 1217

In [14]:
print(matches_df['Division'].unique())

['F1' 'F2' 'T1' 'D1' 'D2' 'B1' 'E2' 'E1' 'N1' 'P1' 'E0' 'I2' 'SP2' 'SP1'
 'I1' 'E3' 'SC0' 'SC1' 'SC2' 'SC3' 'G1' 'EC' 'USA' 'SWE' 'NOR' 'IRL' 'BRA'
 'ARG' 'MEX' 'JAP' 'RUS' 'POL' 'DEN' 'ROM' 'AUT' 'SUI' 'FIN' 'CHN']

In [28]:
epl_df = matches_df[matches_df['Division'].isin(['E0'])].copy()

In [29]:
epl_df

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway,FTResult,HTHome,HTAway,HTResult,HomeShots,AwayShots,HomeTarget,AwayTarget,HomeFouls,AwayFouls,HomeCorners,AwayCorners,HomeYellow,AwayYellow,HomeRed,AwayRed,OddHome,OddDraw,OddAway,MaxHome,MaxDraw,MaxAway,Over25,Under25,MaxOver25,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
154,E0,2000-08-19,NaN,Charlton,Man City,1608.77,1579.99,0.0,0.0,0.0,0.0,4.0,0.0,H,2.0,0.0,H,17.0,8.0,14.0,4.0,13.0,12.0,6.0,6.0,1.0,2.0,0.0,0.0,2.00,3.00,3.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1396,0.0346,0.2085,0.0100,0.2939,0.3134
155,E0,2000-08-19,NaN,Chelsea,West Ham,1800.17,1681.36,0.0,0.0,0.0,0.0,4.0,2.0,H,1.0,0.0,H,17.0,12.0,10.0,5.0,19.0,14.0,7.0,7.0,1.0,2.0,0.0,0.0,1.47,3.40,5.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0702,0.0742,0.0099,0.0823,0.0387,0.7247
156,E0,2000-08-19,NaN,Coventry,Middlesbrough,1635.61,1679.18,0.0,0.0,0.0,0.0,1.0,3.0,A,1.0,1.0,D,6.0,16.0,3.0,9.0,15.0,21.0,8.0,4.0,5.0,3.0,1.0,0.0,2.15,3.00,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8114,0.0316,0.0103,0.0731,0.0319,0.0417
157,E0,2000-08-19,NaN,Derby,Southampton,1636.08,1630.02,0.0,0.0,0.0,0.0,2.0,2.0,D,1.0,2.0,A,6.0,13.0,4.0,6.0,11.0,13.0,5.0,8.0,1.0,1.0,0.0,0.0,2.00,3.10,3.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0272,0.0390,0.0467,0.0100,0.0961,0.7810
158,E0,2000-08-19,NaN,Leeds,Everton,1782.55,1685.55,0.0,0.0,0.0,0.0,2.0,0.0,H,2.0,0.0,H,17.0,12.0,8.0,6.0,21.0,20.0,6.0,4.0,1.0,3.0,0.0,0.0,1.65,3.30,4.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.7772,0.0994,0.0140,0.0429,0.0119,0.0546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230506,E0,2025-05-25,16:00:00,Newcastle,Everton,1882.33,1776.20,4.0,7.0,7.0,7.0,0.0,1.0,A,0.0,0.0,D,17.0,14.0,6.0,6.0,12.0,9.0,12.0,3.0,1.0,4.0,0.0,0.0,1.32,5.60,8.77,1.36,5.85,9.50,1.50,2.55,1.53,2.65,-1.5,1.93,1.93,0.0276,0.0613,0.2894,0.0100,0.5967,0.0150
230507,E0,2025-05-25,16:00:00,Nott'm Forest,Chelsea,1799.76,1880.42,5.0,8.0,6.0,12.0,0.0,1.0,A,0.0,0.0,D,10.0,6.0,2.0,2.0,10.0,11.0,7.0,4.0,2.0,2.0,0.0,0.0,3.09,3.72,2.20,3.20,3.85,2.25,1.67,2.21,1.72,2.26,0.3,1.93,1.93,0.1250,0.7378,0.0139,0.0637,0.0291,0.0305
230508,E0,2025-05-25,16:00:00,Southampton,Arsenal,1557.66,1985.45,1.0,2.0,4.0,8.0,1.0,2.0,A,0.0,1.0,A,7.0,23.0,2.0,8.0,7.0,8.0,5.0,8.0,0.0,0.0,0.0,0.0,9.45,5.83,1.29,11.00,6.11,1.31,1.47,2.64,1.50,2.80,1.5,2.03,1.83,0.0105,0.0098,0.0098,0.9324,0.0276,0.0098
230509,E0,2025-05-25,16:00:00,Tottenham,Brighton,1784.55,1797.83,1.0,1.0,7.0,10.0,1.0,4.0,A,1.0,0.0,H,4.0,23.0,2.0,8.0,13.0,8.0,2.0,11.0,3.0,1.0,0.0,0.0,4.23,4.43,1.71,4.38,4.55,1.73,1.32,3.34,1.34,3.55,0.8,2.00,1.85,0.2559,0.0320,0.0136,0.4660,0.1900,0.0425
230510,E0,2025-05-25,16:00:00,Wolves,Brentford,1739.45,1820.23,0.0,6.0,6.0,12.0,1.0,1.0,D,0.0,1.0,A,18.0,13.0,6.0,7.0,7.0,9.0,8.0,3.0,2.0,1.0,0.0,0.0,2.71,3.76,2.43,2.77,3.85,2.48,1.50,2.55,1.53,2.63,0.0,2.03,1.83,0.0302,0.1610,0.0306,0.1010,0.6641,0.0131